/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SGHDF5DataSetupWizardDialog.java
 *
 * Created on 2010/12/28, 10:50:10
 */

package jp.riken.brain.ni.samuraigraph.application;

import java.util.List;
import java.util.Map;

import javax.swing.JButton;
import javax.swing.SwingUtilities;

import jp.riken.brain.ni.samuraigraph.base.SGDataColumnInfoSet;
import jp.riken.brain.ni.samuraigraph.base.SGTextField;
import jp.riken.brain.ni.samuraigraph.data.SGDataSetupPanel;
import jp.riken.brain.ni.samuraigraph.data.SGDataUtility;
import jp.riken.brain.ni.samuraigraph.data.SGIDataInformationKeyConstants;
import jp.riken.brain.ni.samuraigraph.data.SGMDArrayDataSetupPanel;
import jp.riken.brain.ni.samuraigraph.data.SGMDArrayFile;

/**
 * A wizard dialog to setup HDF5 data when it is added.
 */
public class SGMDArrayDataSetupWizardDialog extends SGDataSetupWizardDialog {
	
	private static final long serialVersionUID = -7084184295273722806L;
	
	/** Creates new form SGHDF5DataSetupWizardDialog */
    public SGMDArrayDataSetupWizardDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mMDArrayDataSetupPanel = new jp.riken.brain.ni.samuraigraph.data.SGMDArrayDataSetupPanel();
        mDataNamePanel = new javax.swing.JPanel();
        mDataNameLabel = new javax.swing.JLabel();
        mDataNameTextField = new jp.riken.brain.ni.samuraigraph.base.SGTextField();
        mButtonPanel = new javax.swing.JPanel();
        mPreviousButton = new jp.riken.brain.ni.samuraigraph.base.SGButton();
        mNextButton = new jp.riken.brain.ni.samuraigraph.base.SGButton();
        mOKButton = new jp.riken.brain.ni.samuraigraph.base.SGButton();
        mCancelButton = new jp.riken.brain.ni.samuraigraph.base.SGButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(mMDArrayDataSetupPanel, gridBagConstraints);

        mDataNamePanel.setLayout(new java.awt.GridBagLayout());

        mDataNameLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        mDataNameLabel.setText("Data Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        mDataNamePanel.add(mDataNameLabel, gridBagConstraints);

        mDataNameTextField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        mDataNamePanel.add(mDataNameTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        getContentPane().add(mDataNamePanel, gridBagConstraints);

        mPreviousButton.setText("<Prev");
        mPreviousButton.setFont(new java.awt.Font("Dialog", 1, 12));
        mButtonPanel.add(mPreviousButton);

        mNextButton.setText("Next>");
        mNextButton.setFont(new java.awt.Font("Dialog", 1, 12));
        mButtonPanel.add(mNextButton);

        mOKButton.setText("OK");
        mOKButton.setFont(new java.awt.Font("Dialog", 1, 12));
        mButtonPanel.add(mOKButton);

        mCancelButton.setText("Cancel");
        mCancelButton.setFont(new java.awt.Font("Dialog", 1, 12));
        mButtonPanel.add(mCancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(mButtonPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected JButton getPreviousButton() {
    	return this.mPreviousButton;
    }

    @Override
    protected JButton getNextButton() {
    	return this.mNextButton;
    }

    @Override
    protected JButton getOKButton() {
    	return this.mOKButton;
    }

    @Override
    protected JButton getCancelButton() {
    	return this.mCancelButton;
    }

	@Override
	protected SGDataSetupPanel getDataSetupPanel() {
		return this.mMDArrayDataSetupPanel;
	}

	@Override
	protected SGTextField getDataNameTextField() {
		return this.mDataNameTextField;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mButtonPanel;
    private jp.riken.brain.ni.samuraigraph.base.SGButton mCancelButton;
    private javax.swing.JLabel mDataNameLabel;
    private javax.swing.JPanel mDataNamePanel;
    private jp.riken.brain.ni.samuraigraph.base.SGTextField mDataNameTextField;
    private jp.riken.brain.ni.samuraigraph.data.SGMDArrayDataSetupPanel mMDArrayDataSetupPanel;
    private jp.riken.brain.ni.samuraigraph.base.SGButton mNextButton;
    private jp.riken.brain.ni.samuraigraph.base.SGButton mOKButton;
    private jp.riken.brain.ni.samuraigraph.base.SGButton mPreviousButton;
    // End of variables declaration//GEN-END:variables

    /**
     * Sets the multidimensional array data.
     * 
     * @param mdFile
     *            multidimensional array file
     * @param dataType
     *            type of data
     * @param colInfoSet
     *            data columns
     * @param infoMap
     *            a map of information
     * @param showDefault
     *            a flag whether to show default column type
     * @return true if succeeded
     */
    public boolean setData(SGMDArrayFile mdFile, String dataType,
            SGDataColumnInfoSet colInfoSet,
            Map<String, Object> infoMap, final boolean showDefault) {

    	// set the title
    	this.setupTitle(dataType);

        if (this.mMDArrayDataSetupPanel.setData(mdFile, dataType, colInfoSet,
        		infoMap, showDefault) == false) {
            return false;
        }
        
        // set data name
        String name = (String) infoMap.get(SGIDataInformationKeyConstants.KEY_DATA_NAME);
        this.setDataName(name);

        // set visible of next button
        if (SGDataUtility.isSXYTypeData(dataType)) {
            this.getNextButton().setVisible(true);
        } else {
            this.getNextButton().setVisible(false);
        }
        
        // enable the OK button
        this.getOKButton().setEnabled(true);
        this.getNextButton().setEnabled(true);

        // packs this dialog
        SwingUtilities.invokeLater(new Runnable() {
        	public void run() {
                pack();
        	}
        });

        return true;
    }
    
    public List<String> getPickUpDatasetName() {
    	return ((SGMDArrayDataSetupPanel) this.getDataSetupPanel()).getSXYDataPickUpDatasetName();
    }
    
    public Map<String, Integer> getPickupDimensionIndexMap() {
    	return ((SGMDArrayDataSetupPanel) this.getDataSetupPanel()).getSXYDataPickUpDimensionIndexMap();
    }

    /**
     * Returns whether stride of data arrays is available.
     * 
     * @return true if stride of data arrays is available
     */
    public boolean isStrideAvailable() {
    	return this.mMDArrayDataSetupPanel.isStrideAvailable();
    }
}
